// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skuqrnnnmharktokpixf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdXFybm5ubWhhcmt0b2twaXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDczMjQsImV4cCI6MjA2ODkyMzMyNH0.iTJzd5j3J2aSim4W6JBgQ0gyYm5zM1DdTtjU_MVIU-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});